### ISSUE TITLE
Understanding why a version of a package is missing

### ISSUE THREAD

**Issue by maroneze** [ocaml-opam/opam-repository-mingw#7]
Hello,

I'm trying to understand why the package `why3.1.6.0` is not currently available for mingw. I'm assuming packages from `opam-repository` are automatically made available here by default, but I'm not sure.

I was using the old fdopen-based URL, so I changed to this ocaml-opam one, did `opam update`, but still nothing. I tried creating a new `ocaml-variants.4.14.1+mingw64c` switch, but it also didn't help.

I assumed the package must not be building under Cygwin, but if I clone it from git and compile it, it seems to work. It also doesn't have any windows-specific constraints.

So, in the end, I don't know why it is not available, and if there is something I could do to make it available. I need it as a dependency to another package, so manually compiling it is not very useful in the end.

**Comment by hhugo** [comment]
What does `opam remote -v` give you ? do you have the default repo enabled ?

**Comment by maroneze** [comment]
```
$ opam remote -v --all
# Repository # Url                                                       # Switches(rank)
default      git+https://github.com/ocaml-opam/opam-repository-mingw.git <default>(1) 4.14.1+mingw64(1) 4.14.1+mingw64c(1) 4.14.0+mingw64c(1)
```

Thanks for the indication, I thought that this repository here was somehow "magically tracking" the default one (in the past, I managed to get all recent packages like that, and never really thought about it).

I added `https://opam.ocaml.org` as a repository, did `opam update`, and now `why3.1.6.0` does show up. I then tried installing it, but now I have 

```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - why3.1.6.0
```

I can `wget` the file and it is in my cache (running `opam install --debug why3.1.6.0` does show it, the file has been downloaded).

The last task displayed before doing a `rmdir` and erroring out is:

```
00:05.343  PARALLEL               Next task in job 2: C:\OCaml64\bin\tar.exe xfz /home/user/.opam/download-cache/md5/6b/6b449abe1e485d6f3c12f81c59fc186c -C /tmp/
opam-9360-4438d8
```

So could it be the `tar` command that fails? If I try it manually, it does output some errors such as:

```
tar: why3-1.6.0/bench/valid/wpcalls.mlw: Cannot change mode to rwxr-xr-x: Not a directory
```

But this happens with all symbolic links in the archive, and also happens for older archives, such as `why3.1.5.1`, which is available via this repository. So either someone fixed such issues manually, or this is unrelated to the problem.

I'm not sure how to proceed from here. Do you have any other suggestions?

**Comment by hhugo** [comment]
Could it be related to https://github.com/ocaml/opam-repository/issues/23954 ..

**Comment by maroneze** [comment]
Probably! I commented there, in case the symbolic link information could be helpful.

**Comment by dra27** [comment]
The underlying issue was indeed the symlink problem (and thanks again for the diagnosis on that, @maroneze 🙂)

>  I'm assuming packages from `opam-repository` are automatically made available here by default, but I'm not sure.

That's not the case - apart from point releases of 4.14.x, the only changes in this repository are to existing package versions, mirroring changes in upstream ocaml/opam-repository. To get _new_ releases of packages, you need to ocaml/opam-repository (see also [this Discuss post](https://discuss.ocaml.org/t/sunsetting-opam-repository-mingw/11632)).

**Comment by maroneze** [comment]
Sorry for coming back to this question, but I just want to confirm that I understand the expected workflow.

So, I'm *still* trying to get `why3.1.6.0` installed on Cygwin. I added `https://opam.ocaml.org` as a remote, and now the package is available. I tried to install it and the `./configure` script failed. I downloaded the sources and tried to compile manually, and I found the cause in the `configure` script:

```sh
      OCAMLFINDLIB=$(ocamlfind printconf stdlib)
      if test "$OCAMLFINDLIB" != "$OCAMLLIB"; then
         found_ocamlfind=no
         reason_ocamlfind=" (incompatible with OCaml)"
         echo "but your ocamlfind is not compatible with your ocamlc:"
         echo "ocamlfind: $OCAMLFINDLIB, ocamlc: $OCAMLLIB"
```

In the first line, we assign the result of `ocamlfind printconf stdlib` to `OCAMLFIND`. And this *seems* to work, even if we print the variable afterwards. But this being ~~hell~~ Windows, *of course* it had to add a `\r` to the end, nearly invisibly, and making the test `"$OCAMLFINDLIB" != "$OCAMLLIB"` fail miserably.

Ok, great, so the code is buggy on Windows. What should be done in this case?

1. Should there be some magical tool or script that, on Cygwin, automatically removes such `\r`s and makes things work as people expect? And that I somehow skipped or disabled, and so I should do it otherwise to get it working?
2. Should I report to the why3 developers, so that they can fix it to work on Windows as well? It's probably the best choice, but this could entail lots of busywork for packages using such shell scripts, and it's hard to debug without having Cygwin yourself; this is like a tricky interview question, unless you are used to these things you will never think of them in advance. Still, if the idea is "test on Windows or add `{os != "windows"}` to `available` seems to be the "expected" one nowadays;
3. Should I instead add an entry to the `patches` opam field, with a Windows-specific patch for such cases, and submit it directly to `opam-repository` ? This solution places less burden on the developers, but forces Cygwin users to find and fix issues by themselves. Still, it seems like a viable solution;
4. Should I just wait for opam 2.2 to be released, and such issues will be automatically handled by it? At least these `\r` ones, which seem often present?

I believe solution 2 is the expected one, but before reporting bugs upstream, I'd like to confirm that this is the case. I had the impression that, in the past, Cygwin tools automatically did such CR-stripping, but maybe I misremember it.

**Comment by dra27** [comment]
> 1. Should there be some magical tool or script that, on Cygwin, automatically removes such `\r`s and makes things work as people expect? And that I somehow skipped or disabled, and so I should do it otherwise to get it working?

Indeed - the magical tool here is either to avoid shell-scripting for configuration (e.g. using configurator, or even an OCaml script) or in this case simply adding `OCAMLFINDLIB=$(ocamlfind printconf stdlib | tr -d '\r')` which is portable.

> 2. Should I report to the why3 developers, so that they can fix it to work on Windows as well?

Yes, that's the fix that's necessary. If targeting Windows is a concern, the effort spent avoiding shell scripts usually pays off further down the line (this kind of thing doesn't happen anywhere near as often if you're processing the output using OCaml's string processing, for example).

> It's probably the best choice, but this could entail lots of busywork for packages using such shell scripts

Yes, indeed, but...

> and it's hard to debug without having Cygwin yourself;

... ocaml/setup-ocaml, GitHub Actions etc. can be used here. 

> this is like a tricky interview question, unless you are used to these things you will never think of them in advance.

That definitely sounds like the interview from hell 🙂

> Still, if the idea is "test on Windows or add `{os != "windows"}` to `available` seems to be the "expected" one nowadays;

There's definitely no need to add `os != "win32"` just because it's not _yet_ been tested on Windows (i.e. I think it's very bad to constrain away a working version of a package from Windows just because it hasn't been tested). opam-repository's fine to have availability and depends updated further down the line if the first person to try it on Windows finds it's broken.

> 3. Should I instead add an entry to the `patches` opam field, with a Windows-specific patch for such cases, and submit it directly to `opam-repository` ? This solution places less burden on the developers, but forces Cygwin users to find and fix issues by themselves. Still, it seems like a viable solution;

This is the change (which was already policy in opam-repository) - the patch must go upstream first. There might then be a decision to patch the existing package pending a new release, but it's very unusual for patches to be carried _only_ in opam-repository. The normal thing here would be to patch `why3` upstream, release a new version and update all the old versions in opam-repository to have `os != "win32"` (unless there's a reason to need to back-port the patch).

> 4. Should I just wait for opam 2.2 to be released, and such issues will be automatically handled by it? At least these `\r` ones, which seem often present?

opam 2.2 isn't magically going to fix this. This worked before because opam-repository-mingw carries a vast amount of non-upstreamed patches in packages which made changes like this. It's not sustainable, though - it means that `why3` before didn't work _on Windows_, it worked specifically on "OCaml for Windows as packaged through opam-repository-mingw". That was fine while someone else was willing to maintain it, but it's a lot of moving parts.

As far as I can see, why3 has always worked in opam-repository-mingw ... that line in `configure` has been present since the oldest version of why3 in opam (11 years ago), so the rationale here is that it _could_ have been fixed a long time ago, but a non-upstreamed workaround in another package, means that no one knew that it was broken.

> I believe solution 2 is the expected one, but before reporting bugs upstream, I'd like to confirm that this is the case. I had the impression that, in the past, Cygwin tools automatically did such CR-stripping, but maybe I misremember it.

Cygwin did change some handling with CRs and became more pedantic (some time ago, now), but that wouldn't have affected this particular case. In particular, Cygwin's grep used to strip out CRs but they stopped on portability grounds.

On the "workarounds" (there are various internal tweaks like this in patches in opam-repository-mingw), the problem I have (and is why I'm certainly not willing to maintain them myself) is that they don't actually _fix_ the underlying problems or, sometimes worse, they actually make diagnosing other bugs harder, as they add layers of "difference" that are easy to forget about (like when your packages are inexplicably selecting the wrong C compiler...).

The very real issue in the past (I mean in pre-opam days) is that getting patches for Windows upstreamed was very slow and often impossible. However, that's not where we are today, so while I realise there will be a fair old bit of pain dealing with these papercuts, I anticipate that it will be possible to get patches in upstream so that we don't have to carry all these downstream patches any longer.
